version: '3'
services:
  paper-qa-bert-webapp6:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_URL=${API_URL:-http://localhost:5000}
    ports:
      - "4200:80"
    environment:
      - API_URL=${API_URL:-http://localhost:5000}
